context:
  welcome_card:
    title: Coffeekraken HTML Boilerplate
    description: Base HTML files and folder structure with complete build process (js, sass, image compression, etc...) built in
    button:
      label: Open google
